apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        #cluster port
      targetPort: 80  #container port
      nodePort: 30001
  type: NodePort