apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: qmai0802/web2:1.0
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web2-service
spec:
  type: ClusterIP  
  selector:
    app: web2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080